<a href="https://colab.research.google.com/github/kaveriiii/Animation-Nation/blob/master/facebookDSBDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("dataset_Facebook.csv",sep=';')
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [ ]:
df.describe()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,500.000000,500.000000,500.000000,500.000000,500.000000,499.000000,500.00000,5.000000e+02,500.000000,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.00000,499.000000,496.000000,500.000000
mean,123194.176000,1.880000,7.038000,4.150000,7.840000,0.278557,13903.36000,2.958595e+04,920.344000,798.772000,1415.130000,1.676638e+04,6585.488000,609.986000,7.48200,177.945892,27.266129,212.120000
std,16272.813214,0.852675,3.307936,2.030701,4.368589,0.448739,22740.78789,7.680325e+04,985.016636,882.505013,2000.594118,5.979102e+04,7682.009405,612.725618,21.18091,323.398742,42.613292,380.233118
min,81370.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.00000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.00000,0.000000,0.000000,0.000000
25%,112676.000000,1.000000,4.000000,2.000000,3.000000,0.000000,3315.00000,5.694750e+03,393.750000,332.500000,509.250000,3.969750e+03,2181.500000,291.000000,1.00000,56.500000,10.000000,71.000000
50%,129600.000000,2.000000,7.000000,4.000000,9.000000,0.000000,5281.00000,9.051000e+03,625.500000,551.500000,851.000000,6.255500e+03,3417.000000,412.000000,3.00000,101.000000,19.000000,123.500000
75%,136393.000000,3.000000,10.000000,6.000000,11.000000,1.000000,13168.00000,2.208550e+04,1062.000000,955.500000,1463.000000,1.486050e+04,7989.000000,656.250000,7.00000,187.500000,32.250000,228.500000
max,139441.000000,3.000000,12.000000,7.000000,23.000000,1.000000,180480.00000,1.110282e+06,11452.000000,11328.000000,19779.000000,1.107833e+06,51456.000000,4376.000000,372.00000,5172.000000,790.000000,6334.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 19 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   Page total likes                                                     500 non-null    int64
 1   Type                                                                 500 non-null    object
 2   Category                                                             500 non-null    int64
 3   Post Month                                                           500 non-null    int64
 4   Post Weekday                                                         500 non-null    int64
 5   Post Hour                                                            500 non-null    int64
 6   Paid                                                                 499 non-null    float64
 7   Lifetime Post Total Reach                                            500 non-null    int64
 8   Lifetime Post Total Impressions                                      500 non-null    int64
 9   Lifetime Engaged Users                                               500 non-null    int64
 10  Lifetime Post Consumers                                              500 non-null    int64
 11  Lifetime Post Consumptions                                           500 non-null    int64
 12  Lifetime Post Impressions by people who have liked your Page         500 non-null    int64
 13  Lifetime Post reach by people who like your Page                     500 non-null    int64
 14  Lifetime People who have liked your Page and engaged with your post  500 non-null    int64
 15  comment                                                              500 non-null    int64
 16  like                                                                 499 non-null    float64
 17  share                                                                496 non-null    float64
 18  Total Interactions                                                   500 non-null    int64
dtypes: float64(3), int64(15), object(1)
memory usage: 74.3+ KB

In [ ]:
df.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [ ]:
df.tail()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [ ]:
df1 = df.loc[10:30]
df1

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
10,139441,Status,2,12,5,10,0.0,21744,42334,4258,4100,4540,37849,18952,3798,0,233.0,19.0,252
11,139441,Photo,2,12,5,10,0.0,3112,5590,208,127,145,3887,2174,165,0,88.0,18.0,106
12,139441,Photo,2,12,5,10,0.0,2847,5133,193,115,133,3779,2072,152,0,90.0,14.0,104
13,139441,Photo,2,12,5,3,0.0,2549,4896,249,134,168,3631,1917,183,5,137.0,10.0,152
14,138414,Photo,2,12,4,5,1.0,22784,39941,887,337,417,34415,19312,684,2,577.0,20.0,599
15,138414,Status,2,12,3,10,0.0,10060,19680,1264,1209,1425,17272,8548,1162,4,86.0,18.0,108
16,138414,Photo,3,12,3,3,0.0,1722,2981,163,123,148,1868,1050,123,2,40.0,12.0,54
17,138414,Photo,1,12,2,12,1.0,53264,111785,1706,1103,1655,92512,39776,1307,15,678.0,20.0,713
18,138414,Status,3,12,2,3,0.0,3930,7509,130,86,112,5009,2410,101,4,54.0,17.0,75
19,138414,Photo,3,12,1,11,0.0,1591,2825,121,88,111,2116,1161,100,0,34.0,8.0,42
20,138414,Photo,2,12,1,3,0.0,2848,5066,200,142,184,3561,1963,157,3,66.0,12.0,81
21,138414,Photo,1,12,7,10,0.0,1384,2467,15,15,20,2196,1172,15,0,0.0,0.0,0
22,138414,Link,1,12,7,10,0.0,3454,6853,118,104,130,6282,3100,106,0,16.0,2.0,18
23,138414,Photo,3,12,7,3,0.0,2723,4888,176,118,143,2964,1621,143,0,72.0,24.0,96
24,138414,Status,2,12,6,10,0.0,8488,15294,1341,1270,1489,9684,5244,995,3,99.0,19.0,121
25,138458,Status,2,12,6,3,0.0,8284,15104,1521,1462,1711,10266,5372,1200,0,88.0,18.0,106
26,138458,Status,2,12,5,11,0.0,19552,34143,2806,2531,3420,17748,9824,1779,10,412.0,72.0,494
27,138458,Photo,3,12,5,3,0.0,2478,4306,212,124,149,2612,1443,166,0,100.0,17.0,117
28,138895,Photo,2,12,5,3,0.0,9560,18264,973,559,885,9217,4748,621,36,523.0,63.0,622
29,138895,Video,1,12,4,11,1.0,36208,61262,1141,1068,1728,30131,14112,559,18,143.0,13.0,174
30,138895,Photo,2,12,4,2,0.0,4940,9390,385,306,501,5860,2930,273,33,107.0,22.0,162

In [ ]:
df1 = df[["Type","Category","Paid"]].loc[1:18]
df1

      Type  Category  Paid
1   Status         2   0.0
2    Photo         3   0.0
3    Photo         2   1.0
4    Photo         2   0.0
5   Status         2   0.0
6    Photo         3   1.0
7    Photo         3   1.0
8   Status         2   0.0
9    Photo         3   0.0
10  Status         2   0.0
11   Photo         2   0.0
12   Photo         2   0.0
13   Photo         2   0.0
14   Photo         2   1.0
15  Status         2   0.0
16   Photo         3   0.0
17   Photo         1   1.0
18  Status         3   0.0

In [ ]:
df2 = df[["Type","Category","comment"]].loc[1:18]
df2

      Type  Category  comment
1   Status         2        5
2    Photo         3        0
3    Photo         2       58
4    Photo         2       19
5   Status         2        1
6    Photo         3        3
7    Photo         3        0
8   Status         2        0
9    Photo         3        3
10  Status         2        0
11   Photo         2        0
12   Photo         2        0
13   Photo         2        5
14   Photo         2        2
15  Status         2        4
16   Photo         3        2
17   Photo         1       15
18  Status         3        4

In [ ]:
df3 = df[["Type","Category","comment"]].loc[1:18]
df3

      Type  Category  comment
1   Status         2        5
2    Photo         3        0
3    Photo         2       58
4    Photo         2       19
5   Status         2        1
6    Photo         3        3
7    Photo         3        0
8   Status         2        0
9    Photo         3        3
10  Status         2        0
11   Photo         2        0
12   Photo         2        0
13   Photo         2        5
14   Photo         2        2
15  Status         2        4
16   Photo         3        2
17   Photo         1       15
18  Status         3        4

In [ ]:
merge_df = pd.concat([df1,df2,df3])
merge_df

      Type  Category  Paid  comment
1   Status         2   0.0      NaN
2    Photo         3   0.0      NaN
3    Photo         2   1.0      NaN
4    Photo         2   0.0      NaN
5   Status         2   0.0      NaN
6    Photo         3   1.0      NaN
7    Photo         3   1.0      NaN
8   Status         2   0.0      NaN
9    Photo         3   0.0      NaN
10  Status         2   0.0      NaN
11   Photo         2   0.0      NaN
12   Photo         2   0.0      NaN
13   Photo         2   0.0      NaN
14   Photo         2   1.0      NaN
15  Status         2   0.0      NaN
16   Photo         3   0.0      NaN
17   Photo         1   1.0      NaN
18  Status         3   0.0      NaN
1   Status         2   NaN      5.0
2    Photo         3   NaN      0.0
3    Photo         2   NaN     58.0
4    Photo         2   NaN     19.0
5   Status         2   NaN      1.0
6    Photo         3   NaN      3.0
7    Photo         3   NaN      0.0
8   Status         2   NaN      0.0
9    Photo         3   NaN      3.0
10  Status         2   NaN      0.0
11   Photo         2   NaN      0.0
12   Photo         2   NaN      0.0
13   Photo         2   NaN      5.0
14   Photo         2   NaN      2.0
15  Status         2   NaN      4.0
16   Photo         3   NaN      2.0
17   Photo         1   NaN     15.0
18  Status         3   NaN      4.0
1   Status         2   NaN      5.0
2    Photo         3   NaN      0.0
3    Photo         2   NaN     58.0
4    Photo         2   NaN     19.0
5   Status         2   NaN      1.0
6    Photo         3   NaN      3.0
7    Photo         3   NaN      0.0
8   Status         2   NaN      0.0
9    Photo         3   NaN      3.0
10  Status         2   NaN      0.0
11   Photo         2   NaN      0.0
12   Photo         2   NaN      0.0
13   Photo         2   NaN      5.0
14   Photo         2   NaN      2.0
15  Status         2   NaN      4.0
16   Photo         3   NaN      2.0
17   Photo         1   NaN     15.0
18  Status         3   NaN      4.0

In [ ]:
sort_df = df.sort_values(["comment"])
sort_df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119
111,136736,Photo,1,10,6,8,0.0,1261,2158,37,37,49,1911,1077,33,0,NaN,NaN,0
276,126424,Photo,3,7,3,4,1.0,2316,3611,722,716,862,2545,1529,372,0,25.0,5.0,30
282,126345,Status,2,6,7,11,0.0,12044,20327,2240,2193,3599,17717,10400,2119,0,104.0,13.0,117
286,126141,Photo,1,6,5,11,1.0,2431,4180,389,383,7980,3963,2301,342,0,15.0,3.0,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228,131728,Photo,2,7,4,3,0.0,14824,21863,868,591,966,13498,8560,650,64,367.0,25.0,456
288,126141,Photo,1,6,4,12,0.0,20896,29062,1418,1038,2048,19738,13656,998,103,469.0,33.0,605
168,135428,Photo,1,9,3,10,0.0,41984,68290,3370,2420,4074,34802,20928,2126,144,1622.0,208.0,1974
460,92507,Photo,3,2,1,13,0.0,55520,665792,4544,3586,6624,648611,47488,3430,146,1546.0,181.0,1873
244,130791,Photo,2,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.0,6334

In [ ]:
sort_df = df.sort_values(["comment","Type","Category"])
sort_df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
22,138414,Link,1,12,7,10,0.0,3454,6853,118,104,130,6282,3100,106,0,16.0,2.0,18
136,136393,Link,1,10,5,10,0.0,4664,9463,204,182,251,7196,3324,173,0,32.0,16.0,48
149,135713,Link,1,10,6,11,1.0,3616,6887,111,90,118,4263,2138,93,0,24.0,11.0,35
430,100732,Link,1,3,7,14,0.0,2933,5144,24,23,26,3972,2012,19,0,6.0,0.0,6
481,86491,Link,1,1,4,4,1.0,4938,7910,66,63,70,6625,3804,59,0,5.0,2.0,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228,131728,Photo,2,7,4,3,0.0,14824,21863,868,591,966,13498,8560,650,64,367.0,25.0,456
288,126141,Photo,1,6,4,12,0.0,20896,29062,1418,1038,2048,19738,13656,998,103,469.0,33.0,605
168,135428,Photo,1,9,3,10,0.0,41984,68290,3370,2420,4074,34802,20928,2126,144,1622.0,208.0,1974
460,92507,Photo,3,2,1,13,0.0,55520,665792,4544,3586,6624,648611,47488,3430,146,1546.0,181.0,1873
244,130791,Photo,2,7,3,5,1.0,180480,319133,8072,4010,6242,108752,51456,3316,372,5172.0,790.0,6334

In [ ]:
df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,490,491,492,493,494,495,496,497,498,499
Page total likes,139441,139441,139441,139441,139441,139441,139441,139441,139441,139441,...,85979,85979,85979,85093,85093,85093,81370,81370,81370,81370
Type,Photo,Status,Photo,Photo,Photo,Status,Photo,Photo,Status,Photo,...,Photo,Photo,Link,Photo,Photo,Photo,Photo,Photo,Photo,Photo
Category,2,2,3,2,2,2,3,3,2,3,...,3,3,1,3,3,3,2,1,3,2
Post Month,12,12,12,12,12,12,12,12,12,12,...,1,1,1,1,1,1,1,1,1,1
Post Weekday,4,3,3,2,2,1,1,7,7,6,...,6,6,5,1,7,7,5,5,4,4
Post Hour,3,10,3,10,3,9,3,9,3,10,...,11,3,11,2,10,2,8,2,11,4
Paid,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
Lifetime Post Total Reach,2752,10460,2413,50128,7244,10472,11692,13720,11844,4694,...,5280,6184,45920,8412,5400,4684,3480,3778,4156,4188
Lifetime Post Total Impressions,5091,19057,4373,87991,13594,20849,19479,24137,22538,8668,...,8703,10228,5808,13960,9218,7536,6229,7216,7564,7292
Lifetime Engaged Users,178,1457,177,2211,671,1191,481,537,1530,280,...,951,956,753,1179,810,733,537,625,626,564
Lifetime Post Consumers,109,1361,113,790,410,1073,265,232,1407,183,...,911,901,655,1111,756,708,508,572,574,524
Lifetime Post Consumptions,159,1674,154,1119,580,1389,364,305,1692,250,...,1237,1140,763,1632,1003,985,687,795,832,743
Lifetime Post Impressions by people who have liked your Page,3078,11710,2812,61027,6228,16034,15432,19728,15220,4309,...,5757,6085,15766,8632,5654,4750,3961,4742,4534,3861
Lifetime Post reach by people who like your Page,1640,6112,1503,32048,3200,7852,9328,11056,7912,2324,...,3300,3502,10720,5348,3230,2876,2104,2388,2452,2200
Lifetime People who have liked your Page and engaged with your post,119,1108,132,1386,396,1016,379,422,1250,199,...,431,437,220,699,422,392,301,363,370,316
comment,4,5,0,58,19,1,3,0,0,3,...,1,1,0,17,10,5,0,4,7,0
like,79.0,130.0,66.0,1572.0,325.0,152.0,249.0,325.0,161.0,113.0,...,79.0,105.0,128.0,185.0,125.0,53.0,53.0,93.0,91.0,91.0
share,17.0,29.0,14.0,147.0,49.0,33.0,27.0,14.0,31.0,26.0,...,30.0,46.0,9.0,55.0,41.0,26.0,22.0,18.0,38.0,28.0
Total Interactions,100,164,80,1777,393,186,279,339,192,142,...,110,152,137,257,176,84,75,115,136,119

In [ ]:
df.shape

(500, 19)

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
r_arr = arr.reshape(5,2)
r_arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
r_arr1 = np.array(df)
r_arr1

array([[139441, 'Photo', 2, ..., 79.0, 17.0, 100],
       [139441, 'Status', 2, ..., 130.0, 29.0, 164],
       [139441, 'Photo', 3, ..., 66.0, 14.0, 80],
       ...,
       [81370, 'Photo', 1, ..., 93.0, 18.0, 115],
       [81370, 'Photo', 3, ..., 91.0, 38.0, 136],
       [81370, 'Photo', 2, ..., 91.0, 28.0, 119]], dtype=object)

In [ ]:
r_arr2 = r_arr1.reshape(-1)
r_arr2

array([139441, 'Photo', 2, ..., 91.0, 28.0, 119], dtype=object)

In [ ]:
df.isnull()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
mean_value = df["Paid"].mean()
mean_value

0.2785571142284569

In [ ]:
df["Paid"].fillna(value = mean_value, inplace = True)
print(df)

     Page total likes    Type  Category  Post Month  Post Weekday  Post Hour  \
0              139441   Photo         2          12             4          3
1              139441  Status         2          12             3         10
2              139441   Photo         3          12             3          3
3              139441   Photo         2          12             2         10
4              139441   Photo         2          12             2          3
..                ...     ...       ...         ...           ...        ...
495             85093   Photo         3           1             7          2
496             81370   Photo         2           1             5          8
497             81370   Photo         1           1             5          2
498             81370   Photo         3           1             4         11
499             81370   Photo         2           1             4          4

         Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
0    0.000000                       2752                             5091
1    0.000000                      10460                            19057
2    0.000000                       2413                             4373
3    1.000000                      50128                            87991
4    0.000000                       7244                            13594
..        ...                        ...                              ...
495  0.000000                       4684                             7536
496  0.000000                       3480                             6229
497  0.000000                       3778                             7216
498  0.000000                       4156                             7564
499  0.278557                       4188                             7292

     Lifetime Engaged Users  Lifetime Post Consumers  \
0                       178                      109
1                      1457                     1361
2                       177                      113
3                      2211                      790
4                       671                      410
..                      ...                      ...
495                     733                      708
496                     537                      508
497                     625                      572
498                     626                      574
499                     564                      524

     Lifetime Post Consumptions  \
0                           159
1                          1674
2                           154
3                          1119
4                           580
..                          ...
495                         985
496                         687
497                         795
498                         832
499                         743

     Lifetime Post Impressions by people who have liked your Page  \
0                                                 3078
1                                                11710
2                                                 2812
3                                                61027
4                                                 6228
..                                                 ...
495                                               4750
496                                               3961
497                                               4742
498                                               4534
499                                               3861

     Lifetime Post reach by people who like your Page  \
0                                                1640
1                                                6112
2                                                1503
3                                               32048
4                                                3200
..                                                ...
495                                              2876
496                                              2104
497                                              2388
498                                              2452
499                                              2200

     Lifetime People who have liked your Page and engaged with your post  \
0                                                  119
1                                                 1108
2                                                  132
3                                                 1386
4                                                  396
..                                                 ...
495                                                392
496                                                301
497                                                363
498                                                370
499                                                316

     comment    like  share  Total Interactions
0          4    79.0   17.0                 100
1          5   130.0   29.0                 164
2          0    66.0   14.0                  80
3         58  1572.0  147.0                1777
4         19   325.0   49.0                 393
..       ...     ...    ...                 ...
495        5    53.0   26.0                  84
496        0    53.0   22.0                  75
497        4    93.0   18.0                 115
498        7    91.0   38.0                 136
499        0    91.0   28.0                 119

[500 rows x 19 columns]

In [ ]:
df.isnull()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
dff = [df["Post Month"] == 1]
dff

[0      False
 1      False
 2      False
 3      False
 4      False
        ...
 495     True
 496     True
 497     True
 498     True
 499     True
 Name: Post Month, Length: 500, dtype: bool]

In [ ]:
int_by_month = df.groupby(["Post Month"])["Total Interactions"].sum()
int_by_month

Post Month
1      4015
2      6293
3      3494
4     10876
5      9483
6      7728
7     17082
8      7663
9     10026
10    10974
11     8359
12    10067
Name: Total Interactions, dtype: int64